core/views/image.py

* Actually pass the backend value to NativeImaging fallback logging
* Avoid forcing evaluation of log messages

Fix logging format strings

---

requirements.pip

Until the migration away from the deprecated `django-celery` package is
complete, using the current 4.x versions of Celery and Kombu will cause
various errors on startup as @johnscancella recently discovered.

Requirements: use compatible versions of Celery & Kombu

---

core/views/static.py
requirements.pip
setup.cfg
urls.py

This adds a basic health-check endpoint on `/healthz` which can be used by load-balancers, Varnish, etc. It currently includes some basic system info, including a timestamp to identify errors in caching and the uptime for the current process, and does a simple database query so it will hopefully fail if the database connection is unstable.

Add health check

---

core/forms.py
settings_template.py

This data was being cached for what was configured by default as a two month
expiration. This changes these two lists used by form inputs to use
METADATA_TTL_SECONDS which is by default one day.

Forms: cache title & full-text range data using metadata TTL

---

core/context_processors.py

This parallels #163 and uses `METADATA_TTL_SECONDS` for the newspaper information context processor's data as well.

Use METADATA_TTL_SECONDS for newspaper_info context processor

---

loc/templates/base.html
loc/templates/home.html

This makes adds two [resource hints](https://w3c.github.io/resource-hints/) to trigger connection to the CDN server faster and to warm the cache for the homepage tabs. 
Browser support:
* http://caniuse.com/#feat=link-rel-prefetch
* http://caniuse.com/#feat=link-rel-preconnect

Add resource hints

---

core/models.py

CHRONAM-331 Fix Title indexing errors in Chronicling America/
Added code to core/models.py that takes care of empty language list.
Manually tested 1. django-admin pull-titles 2. django-admin index_titles for batches 2016212427 and 
2016212406 
The error in index_titles.log was gone

CHRONAM-331 Fix Title indexing errors in Chronicling America

---

core/batch_loader.py

@myusuf @acdha @johnscancella 
Fixing bugs / LanguageText should be populated along with other
tables, otherwise http://chroniclingamerica.loc.gov/languages/
will always be empty

Fixing bugs / LanguageText should be populated along with other tables

---

core/decorator.py
core/views/image.py

This was added in an attempt to deal with OCR noise:
https://github.com/LibraryOfCongress/chronam/commit/87d0216fdc88ede6a35fed222d551b1f97d94a8f
Unfortunately it also strips non-English text: languages such as Arabic
would be completely removed and non-ASCII characters on the beginning or
end of a line would also be silently stripped.
This commit avoids data loss but does it would likely also be necessary to
review the original impetus for this request and see whether we need to
make the JavaScript highlighting code smarter about matching words ignoring
punctuation.
This would be an important step towards landing something like #108 since we
don't want to have a conditional data path which returns different results.

Remove coordinate reprocessing code

---

.editorconfig
package.json

`.editorconfig` provides default settings which many editors and tools respect (see http://editorconfig.org/)
Prettier can now trivially be installed with NPM and Yarn and, as of https://github.com/prettier/prettier/commit/8f58ca0f4802db62719ef6689bd5fb7c476c7afb, now uses `.editorconfig` to load some of its settings.

Add .editorconfig and prettier

---

README.md
core/decorator.py
core/views/browse.py

* Consistent indentation for URL lists
* Mark URL patterns as pre-formatted text to prevent 
Markdown interpreting the “*” as a bold formatting
instruction and to make copy-and-paste easier
* Minor copy-editing

Tidy README formatting for caching section

---

core/templates/about_api.html
core/templates/reports/ocr.html

Since the OCR dumps were regenerated the notice should be changed.

Update notice regarding regenerated OCR dumps

---

core/views/browse.py
loc/templates/page_print.html

This uses the <a download> attribute and the Content-Disposition header to set a filename which includes the LCCN, date, edition, sequence, etc.
Unfortunately, completing this appears to depend on resolving https://github.com/cantaloupe-project/cantaloupe/issues/301 first.

Set a more informative filename for clipping downloads

---

core/decorator.py
core/views/browse.py
core/views/directory.py
core/views/image.py
core/views/reports.py
core/views/search.py
core/views/static.py
urls.py

This was lightly used since the pages link to the .rdf URLs and since it didn’t set the Vary header consistently the results were confusing based on whether a particular URL had been cached by a different class of client before. Since all of the links and documentation use the non-negotiated .rdf links we can simplify the logic by removing the negotiated views and letting Django’s normal APPEND_SLASH behavior handle any legacy links.

Remove RDF content negotiation

---

conf/default.vcl
core/decorator.py

This code path was fortunately only infrequently used — most of the links generated outside of the RDF payloads use the non-negotiated HTML or RDF URLs — but the source of infrequent bug reports because the response type varies depending on the User-Agent and Accept headers but only one of the five response paths set the Vary header and then only with one of the two headers used in the decision process.

Fix content negotiation for RDF views

---

loc/static/base.css

This avoids the stretching introduced in https://github.com/LibraryOfCongress/chronam/commit/17d63a53347de3e631852fd2172a1caa669dfcb4#diff-d6dd3247bbe5766e339bbdbeaddb0e3aR37 for images which don't have aspect ratios which scale evenly to 200x286px:

Avoid stretching “100 years ago” thumbnails

---

core/views/image.py
loc/templates/page.html
settings_template.py

Now that we're using IIIF for new URLs, we want to be prepared to issue redirects for the old ones. This change adds a `REDIRECT_IMAGES_TO_IIIF` setting which will issue temporary redirects for the image views.

Redirect images to IIIF

---

core/fixtures/initial_data.json

- Update the name associated with awardee "ohi" to be "Ohio History Connection";
- Add new awardee code="vnstcsc" name="University of the Virgin Islands";
- Add new awardee code="wyu" name="University of Wyoming Libraries";
- Add new awardee code="rp" name="Providence Public Library, Providence, RI"
(Please deploy changes to production and internal QR instance. )

Update awardee values for new 2019 awards and name changes

---

requirements.pip

0.4.0 breaks things with python 2.7.5

pin piffle to 0.3.0

---

core/migrations/0008_auto_20211130_1437.py
core/models.py

Adds default values for text fields to allow batch imports to work with mysql 8.
Without default values, loading batches with a MySQL 8 db throws the following error:
`unable to load batch: (1364, "Field 'text' doesn't have a default value")`
This PR adds default values of a blank string and allows the fields modified to be blank.
It also includes to Django generated migration file for this change.

adds default values for text fields

---

core/fixtures/initial_data.json

- Update the name associated with awardee "rp" to be "Rhode Island Digital Newspaper Project";
- Add new awardee code="mb" name="Boston Public Library";

Update awardee values for 2021 awards

---

.pre-commit-config.yaml
core/decorator.py
core/views/search.py

This tells crawlers like Googlebot not to crawl the links obtained from search, which avoids the load on Solr from deep pagination. This does not prevent indexing of the actual detail or listing pages which are listed in the sitemaps and are discoverable without crawling all of the permutations of search parameters.
https://developers.google.com/search/docs/advanced/robots/robots_meta_tag

Set X-Robots-Tag: nofollow, index on search results pages

---

loc/templates/site_base_alt.html

This change will update the link text from "Chronicling America Data Visualizations" to "Maps and Visualizations" in left navigation menu. Change requested by the LC NDNP steering committee.

Update Data Visualizations link text in left nav

---

core/title_pull.py
core/worldcat_overrides/request.py

* Added subclass for SearchAPI Request that allows Chronam to pull titles from updated Worldcat SRU search URL
Pull_Titles script was erroring because OCLC changed the worldcat API search URL to http://worldcat.org/webservices/catalog/search/worldcat/sru when it used to be http://worldcat.org/webservices/catalog/search/sru. 
The WorldCat package (https://github.com/anarchivist/worldcat) that Chronam relies on doesn't have the updated API URL yet; Therefore, I simply subclassed the SearchAPIRequest from WorldCat package on PYPI, updated the URL, and replaced the WorldCat SRURequest in title_pull with the new subclass.
@acdha please let me know of any requests for modification.

Update worldcat api deprecated urls (#1)
